Branding = ""
Description = ""
Stylesheets = ["sizes.css", "theme-light.css", "wide.css", "responsive.css"]
RootStylesheets = ["reset.css", "fonts.css", "layout.css"]
PathName = ""

Nav: {
  HTML:
  File: "nav.md"
}

