#!/bin/zsh
echo "bm      Build manual (personal, not metabuzz). See em"
echo ". doc   Go to Metabuzz Documentation directory"
echo "errdoc  Create documentation for a 4-digit Metabuzz error code, e.g. errdoc 0256"
echo "em      Edit source for personal manual"
echo "eto     Edit todo.md"
echo "ff      Find in Metabuzz *.go source files"
echo "ffs     Find text in Metabuzz stylesheets (theme directory)"
echo "gf      Go Format the code"
echo "mbtest1 Generate test files for all themes, all permutations"
echo "om      Open personal manual.html"
echo ". th    Change to themes directory"
echo "v       Validate a stylesheet"
echo ". wb    Change to website directory"

echo ""
echo "template.html   Blank HTML file with all page elements"

