#!/bin/zsh 
# Create an array of filenames
declare -a themes=(
#	'wide'
#  'debut'
  'debut/gallery'
#	'pillar'
#  'tradesman'
	)

# Create an array of sidebar variations
declare -a sidebars=(
  'left'
  'right'
  'no'
  )

# Light/dark modes
declare -a modes=(
  'dark'
  'light'
)


DIR=~/code/m/cmd/mb/theme-test2
LINKSECTION=$DIR/links.tmp
THEMELIST=$DIR/themelist.tmp
TMPFILE=$DIR/foobar.txt



# Delete the previous dir if present
[ -d $DIR ] && rm -rf $DIR
mb new site $DIR
#
# Create temporary filenames
THEMENAMES=$DIR/themenames.tmp
FILENAMES=$DIR/themefilenames.tmp

# Delete the previous temp files if present
[ -f $THEMENAMES ] && rm $THEMENAMES
[ -f $FILENAMES ] && rm $FILENAMES
INDEX=$DIR/index.md

# Convert the array into a file containing one name per line.
for theme in "${themes[@]}";
do
  echo $theme >> $THEMENAMES
done

# Preserve the unchanged theme names
cp $THEMENAMES $FILENAMES 

# Search and replace theme names in the file to
# become valid filenames, e.g. 'debut/gallery'
# is transformed to 'debut-gallery'
sed -i '' 's/\//\-/' $FILENAMES

# Reinitialize the arrays
themenames=()
themefilenames=()

# Read the contents of the array of names
# from the file, one by one, and concatenate
# to the array.
while IFS= read -r line; do
  themenames+=("$line")
done < $THEMENAMES

# Same for the file names, which are derived
# from the theme names
while IFS= read -r line; do
  themefilenames+=("$line")
done < $FILENAMES

# Loop through all themes named origingally in the $themes
# array.
for ((i = 1; i <= $#themenames; i++))
do
  theme=$themenames[$i] 
  base=$themefilenames[$i] 
  for sidebar in "${sidebars[@]}";
  echo "<a name=\"${theme}\"></a> " >> $LINKSECTION
  echo "<br />**${theme}** " >> $LINKSECTION
  echo "[left sidebar](theme-${theme}-left-light.html) ([dark](theme-${theme}-left-dark.html)) [right sidebar](theme-${theme}-right-light.html) ([dark version](theme-${theme}-right-dark.html)) and [no sidebar](theme-${theme}-no-light.html) ([dark](theme-${theme}-no-dark.html)) " >> $LINKSECTION
  echo "[${theme}](#${theme}) " >> $THEMELIST

  for sidebar in "${sidebars[@]}";
  do
    for mode in "${modes[@]}";
    do
      FILENAME=theme-${base}-${sidebar}-${mode}
        echo "${theme}  ${FILENAME}"

cat <<-EOM > $DIR/$FILENAME.md
---
Theme: ${theme}
Sidebar: ${sidebar}
Mode: ${mode}
---
# Auto-generated test for ${theme} theme

EOM
    # A single variation has been generated
    done
    
  done
# All variations on one theme have been generated
  echo "[Home](./index.html)" >> $LINKSECTION

# All test files have been generated
done
cat $THEMELIST >> $INDEX
cat $LINKSECTION >> $INDEX
mb build $DIR
open $DIR/.mb/pub/index.html







