hello, world.

Here's what we know about the test.
* According to the page this theme is: **{{ .Page.FrontMatter.Theme }}**
* Sidebar should be **{{ .Page.FrontMatter.Sidebar }}** 
* Mode should be **{{ .Page.FrontMatter.Mode }}**

### 64x64 PNG image 
![Logo](eastside-emerald-64x64.png)

## Note
* **Resize this** to check for responsive versions
* Check in all browsers

#### Code example
````
print "hello, world."
````

### Table example
| Page element   | HTML tag        |
|--------------- | --------------- |
| header         | &lt;header&gt;  |
| navbar         | &lt;nav&gt;     |
| article        | &lt;article&gt; |
| sidebar        | &lt;aside&gt;   |
| header         | &lt;header&gt;  |


### HTML form test: Search reddit.com
<form action="https://www.google.com/search" class="searchform" method="get" name="searchform" target="_blank">
<input name="sitesearch" type="hidden" value="reddit.com">
<input autocomplete="on" name="q" placeholder="Search reddit.com" required="required"  type="text">
<button class="button" type="submit">Search</button>
</form>


[Home](./index.html)



