#!/bin/zsh 
# Generates all possible variations of each theme: 
# - Left sidebar, right sidebar no sidebar
# - Light or dark mode
# On success it builds a site with an index that links
# to each variation

# Quit this script if an error occurs
set -e

# Create an array of theme names
declare -a themes=(
	'wide'
  'debut'
  #'debut/gallery'
	'pillar'
  'tradesman'
	)

# Create an array of files required for this test
# They'll get copied from the curent directory
# to the new project
declare -a required=(
  'eastside-emerald-64x64.png'
  'mbtest.inc'
  'mbsite.yaml'
  'homerepair.yaml'
	)

# Create an array of sidebar variations
declare -a sidebars=(
  'left'
  'right'
  'none'
  )

# Light/dark modes
declare -a modes=(
  'dark'
  'light'
)

DIR=~/code/m/cmd/mb/theme-test
LINKSECTION=$DIR/links.tmp
THEMELIST=$DIR/themelist.tmp
TMPFILE=$DIR/foobar.txt

INDEX=$DIR/index.md


# Delete the previous dir if present
[ -d $DIR ] && rm -rf $DIR
mkdir $DIR

# Convert the array into a file containing one name per line.
for filename in "${required[@]}";
do
  cp $filename $DIR
done


mb new site --starters homerepair.yaml --site mbsite.yaml  $DIR
cp mbtest.inc $DIR
#
# Create temporary filenames
THEMENAMES=$DIR/themenames.tmp
FILENAMES=$DIR/themefilenames.tmp

# Delete the previous temp files if present
[ -f $THEMENAMES ] && rm $THEMENAMES
[ -f $FILENAMES ] && rm $FILENAMES
INDEX=$DIR/index.md

# Convert the array into a file containing one name per line.
for theme in "${themes[@]}";
do
  echo $theme >> $THEMENAMES
done

# Preserve the unchanged theme names
cp $THEMENAMES $FILENAMES 

# Search and replace theme names in the file to
# become valid filenames, e.g. 'debut/gallery'
# is transformed to 'debut-gallery'
sed -i '' 's/\//\-/' $FILENAMES

# Reinitialize the arrays
themenames=()
themefilenames=()

# Read the contents of the array of names
# from the file, one by one, and concatenate
# to the array.
while IFS= read -r line; do
  themenames+=("$line")
done < $THEMENAMES

# Same for the file names, which are derived
# from the theme names
while IFS= read -r line; do
  themefilenames+=("$line")
done < $FILENAMES


# Loop through all themes named originally in the $themes
# array.
for ((i = 1; i <= $#themenames; i++))
do
  theme=$themenames[$i] 
  base=$themefilenames[$i] 
  for sidebar in "${sidebars[@]}";
  echo "<a name=\"${theme}\"></a> " >> $LINKSECTION
  echo "<br />**${theme}** " >> $LINKSECTION
  echo "[left sidebar](theme-${theme}-left-light.html) ([dark](theme-${theme}-left-dark.html)) [right sidebar](theme-${theme}-right-light.html) ([dark version](theme-${theme}-right-dark.html)) and [no sidebar](theme-${theme}-none-light.html) ([dark](theme-${theme}-none-dark.html)) " >> $LINKSECTION
  echo "[${theme}](#${theme}) " >> $THEMELIST

  for sidebar in "${sidebars[@]}";
  do
    for mode in "${modes[@]}";
    do
     # Generate a file name like "debut-right-dark"
      # where "debut" is the name of the theme,
      # and "dark" is the theme mode
      # "right" means right sidebar", and "
      FILENAME=theme-${base}-${sidebar}-${mode}

cat <<-EOM > $DIR/$FILENAME.md
---
Theme: ${theme}
Sidebar: ${sidebar}
Mode: ${mode}
---
# Auto-generated test for ${theme} theme
{{ inc "./mbtest.inc" }}
EOM
    # A single variation has been generated
    done
    
  # All variations on one theme have been generated
  done
  echo "[Home](./index.html)" >> $LINKSECTION

# All test files have been generated
done
cat $THEMELIST >> $INDEX
cat $LINKSECTION >> $INDEX
#mb build  --site --testsite.yaml $DIR 
#mb build  $DIR 
mb build  $DIR 
ls -lat $DIR
echo "Press a key to view the site"
read answer

open $DIR/.mb/pub/index.html
ls -lat $DIR
echo "Created theme tests in ${DIR}"
exit 0


# This test suite generates all permuations of a theme
# automatically. But what if a required theme-light.css
# or sidebar-left.css doesn't exist, perhaps because it's
# a nested theme? this genereates empty versions.
addEmptyStylesheets () {
  [ -f ${theme}-light.css ] && touch ${theme}-light.css
  [ -f ${theme}-dark.css ] && touch ${theme}-dark.css
  [ -f ${sidebar}-left.css ] && touch ${sidebar}-left.css
  [ -f ${sidebar}-right.css ] && touch ${sidebar}-right.css
}



