#!/bin/zsh
# Exit if an error occurs
set -e
DIR=~/code/m/cmd/mb/theme-test
rm -rf $DIR
mb new site $DIR
INDEX=$DIR/index.md
LINKSECTION=$DIR/links.tmp
THEMELIST=$DIR/themelist.tmp
TMPFILE=$DIR/foobar.txt

cp site.yaml $DIR/.mb
cp eastside-emerald-64x64.png $DIR
# Create an array of filenames
declare -a themes=(
	'wide'
	'pillar'
  'tradesman'
  'debut'
  'w'
	)
rawthemes=$themes
#
# Since nest themes have slashes in their
# names, like 'debut/gallery', convert
# those slashes to dashes to generate
# test filenames. Delimit filenames with newlines.
for theme in "${themes[@]}";
do
  echo $theme >> $TMPFILE
done
sed -i '' 's/\//\-/' $TMPFILE

# Convert the list of filenames back
# to an array.
# I think I'm overcomplicating this. See https://stackoverflow.com/questions/6723426/looping-over-arrays-printing-both-index-and-value#comment65441853_6723516
themes=()
while IFS= read -r line; do
  themes+=("$line")
done < $TMPFILE


# Create an array of variations
declare -a sidebars=(
  'left'
  'right'
  'no'
  )

# Array of modes
declare -a modes=(
  'dark'
  'light'
)

L=\<
R=\>
# Loop through the array
for theme in "${themes[@]}";
do
  echo "<a name=\"${theme}\"></a> " >> $LINKSECTION
  #echo "### Theme: ${theme}" >> $LINKSECTION
  echo "<br />**${theme}** " >> $LINKSECTION
  echo "[left sidebar](theme-${theme}-left-light.html) ([dark](theme-${theme}-left-dark.html)) [right sidebar](theme-${theme}-right-light.html) ([dark version](theme-${theme}-right-dark.html)) and [no sidebar](theme-${theme}-no-light.html) ([dark](theme-${theme}-no-dark.html)) " >> $LINKSECTION
  echo "[${theme}](#${theme}) " >> $THEMELIST

  for sidebar in "${sidebars[@]}";
  do
    for mode in "${modes[@]}";
    do
      FILENAME=theme-${theme}-${sidebar}-${mode}
      echo ${FILENAME}.md
cat <<-EOM > $DIR/$FILENAME.md
---
Theme: ${theme}
Sidebar: ${sidebar}
Mode: ${mode}
---
# Auto-generated test for ${theme} theme

Here's what we know about the test.
* Theme is **${theme}**. According to frontmatter it's **{{ .Page.FrontMatter.Theme }}**
* Sidebar **${sidebar}**. According to frontmatter it's **{{ .Page.FrontMatter.Sidebar }}** 
* Mode should be **${mode}**

### Wait'll they get a load of this
![Logo](eastside-emerald-64x64.png)
**Note**

* **Resize this** to check for responsive versions
* Check in all browsers

#### Code example
````
print "hello, world."
````

| Page element   | HTML tag        |
|--------------- | --------------- |
| header         | &lt;header&gt;  |
| navbar         | &lt;nav&gt;     |
| article        | &lt;article&gt; |
| sidebar        | &lt;aside&gt;   |
| header         | &lt;header&gt;  |


#### HTML form test: Search reddit.com
<form action="https://www.google.com/search" class="searchform" method="get" name="searchform" target="_blank">
<input name="sitesearch" type="hidden" value="reddit.com">
<input autocomplete="on" name="q" placeholder="Search reddit.com" required="required"  type="text">
<button class="button" type="submit">Search</button>
</form>



[Home](./index.html)

EOM

    # A single variation has been generated
    done
    
  done
# All variations on one theme have been generated
  echo "[Home](./index.html)" >> $LINKSECTION

# All test files have been generated
done
cat $THEMELIST >> $INDEX
cat $LINKSECTION >> $INDEX
mb build $DIR
open $DIR/.mb/pub/index.html

