Author:
    Full-Name: ""
    URL: ""
    Role: ""
Authors: []
Base-Path: ""
Branding: ""
Company:
    Name: "Eastside Emerald Something"
    URL: ""
    HeaderLogo: "eastside-emerald-100x100.png"
Exclude-Dirs: []
Exclude-Extensions: []
Ganalytics: ""
Head-Tags: []
HTML-start-file: <!DOCTYPE html><HTML lang=
HTML-end-file: |-
    </body>
    </html>
Language: en
Mode: ""
Social:
    Deviant-Art: ""
    Facebook: ""
    GitHub: ""
    GitLab: ""
    Instagram: ""
    LinkedIn: ""
    Pinterest: ""
    Reddit: ""
    Tumbler: ""
    Twitter: ""
    Weibo: ""
    YouTube: ""
Sidebar: ""
Theme: ""
Starters: {}
List: null
