Author:
    Full-Name: ""
    URL: ""
    Role: ""
CoAuthors: []
Base-Path: ""
Branding: ""
Company:
    Name: ""
    address: ""
    address2: ""
    city: ""
    country: ""
    postalcode: ""
    URL: ""
    Header-Logo: ""
Exclude-Dirs: []
Exclude-Extensions: []
filename: /Users/tom/code/m/cmd/mb/mb1204311241/.mb/site.yaml
Ganalytics: ""
Head-Tags: []
Language: en
Markdown-Options:
    Hard-Wraps: false
    Highlight-Style: github
    Heading-IDs: false
Mode: ""
Social:
    Deviant-Art: ""
    Facebook: ""
    GitHub: ""
    GitLab: ""
    Instagram: ""
    LinkedIn: ""
    Pinterest: ""
    Reddit: ""
    TikTok: ""
    Tumbler: ""
    Twitter: ""
    Weibo: ""
    YouTube: ""
Sidebar: ""
Theme: ""
List: null
