Author:
    Full-Name: Metabuzz
    URL: ""
    Role: ""
Authors: []
Base-Path: ""
Branding: W Starter theme
Company:
    Name: Eastside Emerald Home Repair
    URL: ""
    HeaderLogo: ""
Exclude-Dirs: []
Exclude-Extensions: []
filename: ""
Ganalytics: ""
Head-Tags: []
HTML-start-file: <!DOCTYPE html><HTML lang=
HTML-end-file: |-
    </body>
    </html>
Language: en
Mode: ""
Social:
    Deviant-Art: ""
    Facebook: ""
    GitHub: ""
    GitLab: ""
    Instagram: "Eastsideemeraldhomerepair"
    LinkedIn: ""
    Pinterest: ""
    Reddit: ""
    Tumbler: ""
    Twitter: ""
    Weibo: ""
    YouTube: ""
Sidebar: ""
Theme: w
List: null
