Author:
    Full-Name: ""
    URL: ""
    Role: ""
Authors: []
Base-Path: ""
Branding: ""
Company:
    Name: ""
    address: ""
    address2: ""
    city: ""
    country: ""
    postalcode: ""
    URL: ""
    HeaderLogo: ""
Exclude-Dirs: []
Exclude-Extensions: []
filename: /Users/tom/code/m/cmd/mb/.mb/site.yaml
Ganalytics: ""
Head-Tags: []
HTML-start-file: <!DOCTYPE html><HTML lang=
HTML-end-file: |-
    </body>
    </html>
Language: en
Mode: ""
Social:
    Deviant-Art: ""
    Facebook: ""
    GitHub: ""
    GitLab: ""
    Instagram: ""
    LinkedIn: ""
    Pinterest: ""
    Reddit: ""
    Tumbler: ""
    Twitter: ""
    Weibo: ""
    YouTube: ""
Sidebar: ""
Theme: ""
List: null
