Author:
    Full-Name: "Tom Campbell"
    URL: ""
    Role: ""
Authors: []
Branding: "Metabuzz, Inc."
Company:
    Name: "Metabuzz"
    URL: "https://metabuzz.com"
    headerlogo: ""
Exclude-Dirs: []
Exclude-Extensions: []
Ganalytics: ""
Head-Tags: []
Language: en
Mode: ""
Social:
    Deviant-Art: ""
    Facebook: ""
    GitHub: ""
    GitLab: ""
    Instagram: ""
    LinkedIn: ""
    Pinterest: ""
    Reddit: ""
    Tumbler: ""
    Twitter: ""
    Weibo: ""
    YouTube: ""
Sidebar: ""
Theme: ""
List: null
#generate: {}
